name: fs_shim_test
description: fs_shim test context helpers
version: 0.2.1
author: Alexandre Roux Tekartik <alex@tekartik.com>
dependencies:
  fs_shim: any
  dev_test: any
  test: any
  platform_context:
    git: git://github.com/tekartik/platform_context.dart
dev_dependencies:
  chrome_travis:
    git: git://github.com/tekartik/chrome_travis.dart
    version: '>=0.1.3'
#  tekartik_pub:
#    git: git://github.com/tekartik/tekartik_pub.dart
dependency_overrides:
  fs_shim:
    git: git://github.com/tekartik/fs_shim.dart
#  fs_shim:
#    path: ../fs_shim.dart
