name: fs_shim_test
description: fs_shim test context helpers
version: 0.2.0
author: Alexandre Roux Tekartik <alex@tekartik.com>
dependencies:
  fs_shim: any
  dev_test: any
  test: any
  platform_context:
    git: git://github.com/tekartik/platform_context.dart
dev_dependencies:
  tekartik_pub:
    git: git://github.com/tekartik/tekartik_pub.dart
