name: fs_idb_sqflite
description: Test fs on idb and sqflite.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  sqflite_common_ffi: '>=2.3.1'
  sqflite_common: '>=2.5.0+2'
  fs_shim: '>=2.1.0-7'
  idb_shim: '>=2.3.2'
  path:
  idb_sqflite:
  tekartik_fs_test:
    git:
      url: https://github.com/tekartik/fs_shim.dart
      path: fs_test
      ref: dart3a
    version: '>=0.1.0'
dev_dependencies:
  lints: '>=2.0.0'
  test: '>=1.16.0'

dependency_overrides:
  # fs_shim:
  #  path: ../../../fs_shim.dart/fs
  # tekartik_fs_test:
  #  path: ../../../fs_shim.dart/fs_test
