name: fs_idb_sqflite
description: Test fs on idb and sqflite.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.9.0

dependencies:
  sqflite_common_ffi: ">=2.3.4"
  sqflite_common: '>=2.5.0+2'
  fs_shim: ">=2.4.0-1"
  idb_shim: '>=2.3.2'
  path: ">=1.9.0"
  idb_sqflite:
  tekartik_fs_test:
    git:
      url: https://github.com/tekartik/fs_shim.dart
      path: fs_test
      ref: dart3a
    version: '>=0.1.0'
dev_dependencies:
  lints: ">=5.0.0"
  test: ">=1.24.0"

dependency_overrides:
resolution: workspace
  # fs_shim:
  #  path: ../../../fs_shim.dart/fs
  # tekartik_fs_test:
  #  path: ../../../fs_shim.dart/fs_test
