name: fs_idb_sqflite
description: Test fs on idb and sqflite.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  sqflite_common_ffi:
  sqflite_common:
  fs_shim: '>=2.1.0-7'
  idb_shim:
  path:
  idb_sqflite:
  tekartik_fs_test:
    git:
      url: https://github.com/tekartik/fs_shim.dart
      path: fs_test
      ref: dart2_3
    version: '>=0.1.0'
dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

dependency_overrides:
  # fs_shim:
  #  path: ../../../fs_shim.dart/fs
  # tekartik_fs_test:
  #  path: ../../../fs_shim.dart/fs_test
